# -*- coding: utf-8 -*-
"""TrabalhoFinal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rq0dCXcC4lZZzMg7RimtARNP43ywjnCY
"""

!pip install -U gdown langchain langchain-community langchain-openai chromadb openai tiktoken langchain-text-splitters streamlit langchain-openai langchain-google-community pyngrok chardet --quiet

destino_dir="/content/dados_nfe"
persist_dir="/content/chroma_nfe"

import os
from google.colab import userdata
# Pega a chave armazenada nos secrets do Colab
api_key = userdata.get("OPENAI_API_KEY")

# Injeta no ambiente para o LangChain reconhecer
os.environ["OPENAI_API_KEY"] = api_key
# Substitua "sua-chave" pela sua OpenAI API Key

import os
from google.colab import userdata
from pyngrok import ngrok

# 1. PEGA TODOS OS SECRETS AQUI NA CÉLULA
try:
    # Chaves da OpenAI e Google
    os.environ["OPENAI_API_KEY"] = userdata.get("OPENAI_API_KEY")
    os.environ["GCS_API_KEY"] = userdata.get("GCS_API_KEY")
    os.environ["GCS_CX"] = userdata.get("GCS_CX")

    # Chave do Ngrok
    authtoken = userdata.get('NGROK_AUTHTOKEN')
    ngrok.set_auth_token(authtoken)

    print("✅ Secrets carregados no ambiente.")

except Exception as e:
    print(f"❌ Erro ao carregar secrets: {e}")
    print("Verifique se todas as 4 chaves (OPENAI, GCS_API_KEY, GCS_CX, NGROK_AUTHTOKEN) estão salvas corretamente.")


# Mata qualquer túnel ngrok que já esteja rodando
ngrok.kill()

# Roda o app Streamlit em background
!nohup streamlit run agente_interface.py &> streamlit.log &

# Espera para o Streamlit iniciar
import time
print("Aguardando o Streamlit iniciar... ⏳")
time.sleep(5)

# Cria o túnel e mostra o link público (agora autenticado!)
public_url = ngrok.connect(8501)
print("=====================================================================================")
print(f"✅ SEU APLICATIVO ESTÁ NO AR! ACESSE AQUI: {public_url}")
print("=====================================================================================")